name: "E2E Check Runner"
description: "Reusable action to update GitHub Check Runs for E2E tests (in_progress or completed)."

inputs:
    token:
        description: "GitHub token with permissions to update checks"
        required: true

    check-run-id:
        description: "ID of the check run to update"
        required: true

    state:
        description: "One of: in_progress | completed"
        required: true

    job-status:
        description: "Success or failure (required only when state=completed)"
        required: false

    project:
        description: "Project/app name (only used when state=completed)"
        required: false

    preview-url:
        description: "Preview URL (only used when state=completed)"
        required: false

runs:
    using: composite
    steps:
        # =========================================================
        # FIX: safe checkout (does NOT override caller repo)
        # =========================================================
        - name: Checkout action source
          uses: actions/checkout@v4
          with:
              repository: technance-foundation/github-actions
              ref: v1
              path: ./.github/actions/github-actions
              sparse-checkout: |
                  e2e-check
              sparse-checkout-cone-mode: false

        # -----------------------------
        # DEBUG 1: Print inputs
        # -----------------------------
        - name: DEBUG — Print Inputs
          shell: bash
          run: |
              echo "### E2E CHECK — DEBUG (Inputs)"
              echo "state=${{ inputs.state }}"
              echo "check-run-id=${{ inputs.check-run-id }}"
              echo "job-status=${{ inputs.job-status }}"
              echo "project=${{ inputs.project }}"
              echo "preview-url=${{ inputs.preview-url }}"

        # -----------------------------
        # DEBUG 2: Print GitHub env
        # -----------------------------
        - name: DEBUG — GitHub Context
          shell: bash
          run: |
              echo "### E2E CHECK — DEBUG (Context)"
              echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
              echo "GITHUB_JOB=$GITHUB_JOB"
              echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
              echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
              echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
              echo "GITHUB_SHA=$GITHUB_SHA"
              echo "GITHUB_REF=$GITHUB_REF"

        # -----------------------------
        # DEBUG 3: Ensure check run exists
        # -----------------------------
        - name: DEBUG — Validate Check Run Exists
          uses: actions/github-script@v7
          env:
              CHECK_RUN_ID: ${{ inputs.check-run-id }}
          with:
              github-token: ${{ inputs.token }}
              script: |
                  core.info("### E2E CHECK — DEBUG (Check Run Lookup)");
                  const id = Number(process.env.CHECK_RUN_ID);
                  const { owner, repo } = context.repo;

                  try {
                      const res = await github.rest.checks.get({
                          owner, repo, check_run_id: id
                      });
                      core.info("Check Run Found:");
                      core.info(JSON.stringify({
                          id: res.data.id,
                          status: res.data.status,
                          conclusion: res.data.conclusion,
                          name: res.data.name
                      }, null, 2));
                  } catch (err) {
                      core.error("❌ Failed to fetch check run");
                      core.error(err);
                      throw err;
                  }

        # -----------------------------
        # EXECUTION
        # -----------------------------
        - name: Mark check as in_progress
          if: ${{ inputs.state == 'in_progress' }}
          uses: actions/github-script@v7
          env:
              CHECK_RUN_ID: ${{ inputs.check-run-id }}
          with:
              github-token: ${{ inputs.token }}
              script: |
                  const run = require('./.github/actions/github-actions/e2e-check/mark-in-progress.cjs');
                  await run({ github, context, core });

        - name: Complete check
          if: ${{ inputs.state == 'completed' }}
          uses: actions/github-script@v7
          env:
              CHECK_RUN_ID: ${{ inputs.check-run-id }}
              PROJECT: ${{ inputs.project }}
              PREVIEW_URL: ${{ inputs.preview-url }}
              JOB_STATUS: ${{ inputs.job-status }}
          with:
              github-token: ${{ inputs.token }}
              script: |
                  const run = require('./.github/actions/github-actions/e2e-check/complete-check.cjs');
                  await run({ github, context, core });
