name: "E2E Test Runner"
description: "Runs Playwright E2E tests, manages setup, caching, reports, and GitHub Check Runs."

inputs:
    token:
        description: "GitHub token with permissions to update checks"
        required: true

    check-run-id:
        description: "GitHub Check Run ID"
        required: true

    project:
        description: "Project/app name (used for report folder and summary)"
        required: true

    preview-url:
        description: "Preview deployment base URL for the tests (BASE_URL)"
        required: true

    node-version:
        description: "Node.js version"
        default: "22"

    pnpm-version:
        description: "PNPM version"
        default: "10.15.0"

    playwright-version:
        description: "Playwright version (for caching)"
        default: "1.53.2"

    npm-token:
        description: "NPM token for installing private dependencies"
        required: true

runs:
    using: composite
    steps:
        # =========================================================
        # Check out action source WITHOUT wiping caller repo
        # =========================================================
        - name: Checkout action source
          id: checkout-action
          uses: actions/checkout@v4
          with:
              repository: technance-foundation/github-actions
              ref: v1
              path: ./.github/actions/github-actions
              sparse-checkout: |
                  e2e-check
                  e2e-test-runner
              sparse-checkout-cone-mode: false

        # -----------------------------------------------------
        # MARK CHECK AS IN_PROGRESS
        # -----------------------------------------------------
        - name: Mark check as in_progress
          id: mark-in-progress
          uses: technance-foundation/github-actions/e2e-check@v1
          with:
              token: ${{ inputs.token }}
              check-run-id: ${{ inputs.check-run-id }}
              state: in_progress

        # -----------------------------------------------------
        # SETUP & DEPENDENCIES
        # -----------------------------------------------------
        - name: Setup & install (root)
          id: setup
          uses: technance-foundation/github-actions/setup@v1
          with:
              node-version: ${{ inputs.node-version }}
              pnpm-version: ${{ inputs.pnpm-version }}
              npm-token: ${{ inputs.npm-token }}
              pnpm-cache: "write"
              install: "pnpm install --no-frozen-lockfile"
              build: "false"

        # -----------------------------------------------------
        # BROWSER CACHING
        # -----------------------------------------------------
        - name: Cache Playwright browsers
          id: cache-playwright
          uses: actions/cache@v4
          with:
              path: ~/.cache/ms-playwright
              key: ${{ runner.os }}-playwright-${{ inputs.playwright-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-playwright-${{ inputs.playwright-version }}-

        - name: Install Playwright deps + browsers (cache miss)
          id: pw-install
          if: steps.cache-playwright.outputs.cache-hit != 'true'
          shell: bash
          run: pnpm exec playwright install --with-deps chromium

        # -----------------------------------------------------
        # RUN TESTS
        # -----------------------------------------------------
        - name: Run E2E tests
          id: e2e
          shell: bash
          working-directory: apps/${{ inputs.project }}
          env:
              BASE_URL: ${{ inputs.preview-url }}
          run: pnpm run test:e2e

        # -----------------------------------------------------
        # REPORT
        # -----------------------------------------------------
        - name: Upload Playwright report
          id: upload-report
          if: always()
          uses: actions/upload-artifact@v4
          with:
              name: ${{ inputs.project }}-playwright-report
              path: apps/${{ inputs.project }}/playwright-report/
              retention-days: 30

        # -----------------------------------------------------
        # COMPLETE CHECK
        # -----------------------------------------------------
        - name: Complete check
          if: always()
          uses: technance-foundation/github-actions/e2e-check@v1
          with:
              token: ${{ inputs.token }}
              check-run-id: ${{ inputs.check-run-id }}
              state: completed
              job-status: ${{ (steps.checkout-action.outcome == 'success' && steps.mark-in-progress.outcome == 'success' && steps.setup.outcome == 'success' && steps.cache-playwright.outcome == 'success' && (steps.pw-install.outcome == 'success' || steps.pw-install.outcome == 'skipped') && steps.e2e.outcome == 'success' && steps.upload-report.outcome == 'success') && 'success' || 'failure' }}
              project: ${{ inputs.project }}
              preview-url: ${{ inputs.preview-url }}
