name: Release (Changesets + pnpm, auto on main)
description: >
    Fully automated release action that runs on pushes to main.
    Uses Changesets to bump versions, remove .changeset files, commit & push,
    and publish packages with pnpm.

branding:
    icon: package
    color: blue

inputs:
    # Node / pnpm
    node-version:
        description: "Explicit Node.js version"
        default: "20"
        required: false
    pnpm-version:
        description: "pnpm version to install"
        default: "9.0.6"
        required: false
    cache:
        description: "Cache strategy for setup-node (pnpm|npm|yarn|false)"
        default: "pnpm"
        required: false

    # Registry / Auth
    npm-registry:
        description: "NPM registry URL"
        default: "https://registry.npmjs.org"
        required: false
    npm-token:
        description: "NPM token for authentication (optional, required for publishing)"
        required: false

    # Token used for pushing release commits
    push-token:
        description: >
            Token used to push release commits.
            Can be:
            - a user/bot PAT with repo write access, or
            - a GitHub App installation access token.
            If omitted, falls back to GITHUB_TOKEN (may be blocked by branch protection).
        required: false
        default: ""

    # Commands
    install-command:
        description: "Dependency install command"
        default: "pnpm install --frozen-lockfile"
        required: false
    build-command:
        description: "Build command"
        default: "pnpm build"
        required: false
    version-command:
        description: "Changesets version command (bump versions and remove .changeset files)"
        default: "pnpm run bump"
        required: false
    publish-command:
        description: "Publish command (usually pnpm run release or pnpm changeset publish)"
        default: "pnpm run release"
        required: false

    # Misc / Git
    working-directory:
        description: "Working directory to run all commands in"
        required: false
    git-user-name:
        description: "Git user.name for release commit"
        default: "github-actions[bot]"
        required: false
    git-user-email:
        description: "Git user.email for release commit"
        default: "github-actions[bot]@users.noreply.github.com"
        required: false

outputs:
    published:
        description: "Whether a publish occurred"
        value: ${{ steps.set-output.outputs.published }}
    new_version:
        description: "Captured example new version from Changesets status (best effort)"
        value: ${{ steps.set-output.outputs.new_version }}

runs:
    using: composite
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              # Use push-token if provided, otherwise fall back to GITHUB_TOKEN
              token: ${{ inputs.push-token != '' && inputs.push-token || github.token }}
              # Only persist credentials when we are *not* using a custom push-token
              persist-credentials: ${{ inputs.push-token == '' }}

        - name: Setup git
          shell: bash
          run: |
              git config --global user.email "${{ inputs.git-user-email }}"
              git config --global user.name "${{ inputs.git-user-name }}"

        - name: Setup pnpm
          uses: pnpm/action-setup@v4
          with:
              version: ${{ inputs.pnpm-version }}
              run_install: false

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              registry-url: ${{ inputs.npm-registry }}
              cache: ${{ inputs.cache }}
              cache-dependency-path: |
                  **/pnpm-lock.yaml

        - name: Authenticate NPM registry (optional)
          if: ${{ inputs.npm-token != '' }}
          shell: bash
          env:
              NPM_TOKEN: ${{ inputs.npm-token }}
          run: |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

        - name: Install dependencies
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: ${{ inputs.install-command }}

        - name: Build packages
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: ${{ inputs.build-command }}

        # Detect pending changesets
        - name: Check for pending changesets
          id: changeset-status
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              set -e

              if [ ! -d ".changeset" ]; then
                echo "has_changesets=false" >> "$GITHUB_OUTPUT"
                echo "No .changeset directory found; skipping release."
                exit 0
              fi

              # Try to get JSON status; if it fails, assume no changesets.
              if pnpm changeset status --output=release.json 2>/dev/null; then
                RELEASE_COUNT="$(jq -r '.releases | length' release.json || echo 0)"
                if [ "$RELEASE_COUNT" -eq 0 ]; then
                  echo "No pending changesets; skipping release."
                  echo "has_changesets=false" >> "$GITHUB_OUTPUT"
                else
                  echo "Found $RELEASE_COUNT pending releases."
                  echo "has_changesets=true" >> "$GITHUB_OUTPUT"
                  # Best-effort example new version
                  NEW_VERSION="$(jq -r '.releases[0].newVersion // empty' release.json || echo '')"
                  echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
                fi
                rm -f release.json
              else
                echo "changeset status failed or no pending releases; skipping."
                echo "has_changesets=false" >> "$GITHUB_OUTPUT"
              fi

        # Run versioning (bump versions, update changelogs, remove .changeset/*.md)
        - name: Apply version bumps with Changesets
          if: ${{ steps.changeset-status.outputs.has_changesets == 'true' }}
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              set -e
              echo "Running version command: ${{ inputs.version-command }}"
              ${{ inputs.version-command }}

        # Check if versioning actually changed anything
        - name: Check for git changes after versioning
          if: ${{ steps.changeset-status.outputs.has_changesets == 'true' }}
          id: git-diff
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              set -e
              if [ -z "$(git status --porcelain)" ]; then
                echo "No git changes after versioning; skipping commit & publish."
                echo "has_changes=false" >> "$GITHUB_OUTPUT"
              else
                echo "Detected git changes after versioning."
                git status --short
                echo "has_changes=true" >> "$GITHUB_OUTPUT"
              fi

        - name: Commit & push version bump
          if: ${{ steps.changeset-status.outputs.has_changesets == 'true' && steps.git-diff.outputs.has_changes == 'true' }}
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          env:
              GITHUB_REF_NAME: ${{ github.ref_name }}
              PUSH_TOKEN: ${{ inputs.push-token }}
          run: |
              set -e

              COMMIT_MESSAGE="chore(release): publish"
              echo "Committing with message: $COMMIT_MESSAGE"

              git add .
              git commit -m "$COMMIT_MESSAGE"

              CURRENT_BRANCH="${GITHUB_REF_NAME:-main}"

              echo "Rebasing on latest origin/${CURRENT_BRANCH} before push"
              git fetch origin "${CURRENT_BRANCH}"
              git rebase "origin/${CURRENT_BRANCH}"

              # Ensure no GITHUB_TOKEN extraheader is overriding our PAT
              git config --local --unset-all http.https://github.com/.extraheader || true

              if [ -n "$PUSH_TOKEN" ]; then
                echo "Configuring authenticated remote with provided push-token"
                git remote set-url origin "https://x-access-token:${PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
              else
                echo "WARNING: no push-token provided, falling back to GITHUB_TOKEN."
                echo "If the branch is protected and requires a bypass actor, this push may be rejected."
              fi

              echo "Pushing to origin ${CURRENT_BRANCH}"
              set +e
              git push origin "HEAD:${CURRENT_BRANCH}"
              PUSH_EXIT=$?
              set -e

              if [ "$PUSH_EXIT" -ne 0 ]; then
                echo "Initial push failed (exit code $PUSH_EXIT), attempting force push with lease..."
                git push --force-with-lease origin "HEAD:${CURRENT_BRANCH}"
              else
                echo "Push succeeded."
              fi

        - name: Publish packages
          if: ${{ steps.changeset-status.outputs.has_changesets == 'true' && steps.git-diff.outputs.has_changes == 'true' }}
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          env:
              NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
          run: |
              set -e
              echo "Running publish command: ${{ inputs.publish-command }}"
              ${{ inputs.publish-command }}

        - name: Set outputs
          id: set-output
          shell: bash
          run: |
              PUBLISHED="false"
              NEW_VERSION="${{ steps.changeset-status.outputs.new_version }}"

              if [ "${{ steps.changeset-status.outputs.has_changesets }}" = "true" ] && \
                 [ "${{ steps.git-diff.outputs.has_changes }}" = "true" ]; then
                PUBLISHED="true"
              fi

              echo "published=$PUBLISHED" >> "$GITHUB_OUTPUT"
              echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
