name: "Setup Workflow"
description: "A reusable GitHub Action for setting up a `pnpm` repository with for the subsequent steps"

inputs:
    node-version:
        description: "The version of Node.js to use"
        default: "20"
    pnpm-version:
        description: "The version of pnpm to use"
        default: "9.0.6"
    pnpm-cache:
        description: "Cache strategy can be one of `read`, `write`, or `off`"
        default: "write"
    npm-token:
        description: "NPM token for authenticating to the NPM registry"
        required: true
    install:
        description: "Either false to skip or the build command to run, default is `pnpm install --no-frozen-lockfile`"
        default: "pnpm install --no-frozen-lockfile"
    build:
        description: "Either false or the build command to run, default is `pnpm build`"
        default: "pnpm build"
    working-directory:
        description: "The working directory to run the commands in"
        default: "."

runs:
    using: "composite"
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}

        - name: Setup pnpm
          id: pnpm-setup
          uses: pnpm/action-setup@v4
          with:
              version: ${{ inputs.pnpm-version }}
              run_install: false

        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              echo "STORE_PATH<<EOF" >> "$GITHUB_OUTPUT"
              pnpm store path >> "$GITHUB_OUTPUT"
              echo "EOF" >> "$GITHUB_OUTPUT"

        - uses: actions/cache/restore@v4
          if: ${{ inputs.pnpm-cache == 'read' }}
          name: Initialize pnpm cache
          with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-store-${{ hashFiles(format('{0}/**/package.json', inputs.working-directory)) }}-${{ hashFiles(format('{0}/**/pnpm-lock.yaml', inputs.working-directory)) }}
              restore-keys: |
                  ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-store-${{ hashFiles(format('{0}/**/package.json', inputs.working-directory)) }}-
                  ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-store-

        - uses: actions/cache@v4
          if: ${{ inputs.pnpm-cache == 'write' }}
          name: Initialize pnpm cache
          with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-store-${{ hashFiles(format('{0}/**/package.json', inputs.working-directory)) }}-${{ hashFiles(format('{0}/**/pnpm-lock.yaml', inputs.working-directory)) }}
              restore-keys: |
                  ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-store-${{ hashFiles(format('{0}/**/package.json', inputs.working-directory)) }}-
                  ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-store-

        - name: Authenticate NPM registry
          shell: bash
          run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > ~/.npmrc

        - name: Install dependencies
          if: ${{ inputs.install != 'false' }}
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: ${{ inputs.install }}

        - name: Build
          if: ${{ inputs.build != 'false' }}
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: ${{ inputs.build }}
